### ISSUE TITLE
Camera Problem

### ISSUE THREAD

**Issue by reesy42** [thinkoco/c5soc_opencl#11]
Hi thinkoco,
I tested the terasic DE1 Board with the
opencv Camera in example.
I tested 3 Webcams,
1 worked fine 
1 seems to have the wrong sync-rate (or something that makes the picture scrambling)
1 crashed when starting the app.
Is there a way to config the camera driver ?
best regards
 hauke

**Comment by thinkoco** [comment]
@reesy42 yes the UVC carmeas may works fine.Also,you can loard target camera driver by module files(xxx.ko) and check the configuration in main.cpp.

**Comment by reesy42** [comment]
I tried to load the gspca driver manualy with
'modprobe -f gspca_main.ko'
The I get the error 
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/3.18.0-00261-ge5adb7d/modules.dep.bin'
and
modprobe: FATAL: Module gspca_main.ko not found in directory /lib/modules/3.18.0-00261-ge5adb7d
The fact is, that the modules are in '/lib/modules/4.5.0-00185-g3bb556b/kernel/drivers'. So these modules are compiled for the 4.5 kernel version and not for the 3.18 kernel version.
So how can iget drivers for the 3.18 kernel version ?

**Comment by thinkoco** [comment]
@reesy42 yes,  the `4.5.0-00185-g3bb556b` folder is not for kernel 3.18. I just get the file system form a sd image directly. You can build the 3.18.0-00261-ge5adb7d by checking out the commit (e5adb7de821ddbae001c7a70c0f5fe0a50f2d57b) and build the drivers.
[Here](https://github.com/thinkoco/c5soc_opencl/blob/master/HowToBuildSDImage.md#4-build-zimage-and-socfpgadtb) are some guides.

**Comment by thinkoco** [comment]
@reesy42 Also, I am not sure that if all 'gspca' cameras can works well.  UVC cameras will be better.

**Comment by reesy42** [comment]
Thank you for your response,
I've compiled the camera drivers for the 3.18 kernel, with the same problems.
Only one camera works with the uvc driver, the other 2 cameras don't work neither with uvc nor with gspca driver.
By the way on a normal PC Ubuntu linux system both cameras work with the uvc driver.
Have you tried different cameras ?

**Comment by thinkoco** [comment]
@reesy42 I did have try some UVC cameras. They are ok. Also, there are some differences in different UVC cameras,for example pixel format (Mjpeg or YUV), resolution size.In the OpenCL host ,it's YUYV-4:2:2. you can install a guvcview  to get more the camera features.
