### ISSUE TITLE
OpenCL SDK support for Quartus Prime Lite version

### ISSUE THREAD

**Issue by lutherstrike** [thinkoco/c5soc_opencl#18]
Hi @thinkoco,
I want to process an OpenCL project on the DE1SOC board for a class assignment.

After two days of setting a development environment, **it seems like Quartus Prime Lite doesn't support OpenCL SDK.**

Like you can't install OpenCL SDK and Quartus Prime Lite in the same directory(even you don't install the Quartus Prime Standard/Por included in OpenCL SDK), but if installed in separate directories, I can't figure out how to set environment variables properly.
It seems like you made it with Quartus Prime Lite 18.0 in your tutorial.

Do you have any idea to solve this problem?

Thanks,
Luther

**Comment by thinkoco** [comment]
Hi,@lutherstrike 
It 's OK on Ubuntu 18.04 with Quartus Prime Lite 18.1 and OpenCL SDK 18.1 `Stand-Alone Software`  (Standard ).
![image](https://user-images.githubusercontent.com/22982301/70491956-ca58e580-1b3d-11ea-8513-efabd4f00843.png)

Here is my environment-module files for environment variable,
```
  8 module-whatis "sets up access to  Quartus Prime 18.1 lite"
  9 #prereq 
 10 conflict altera
 11 global QSYS_ROOTDIR
 12 
 13 append-path PATH {/opt/intelFPGA_lite/18.1/modelsim_ase/linuxaloem};
 14 append-path PATH {/opt/intelFPGA_lite/18.1/quartus/bin};
 15 append-path PATH {/opt/intelFPGA_lite/18.1/quartus/linux64};
 16 append-path PATH {/opt/intelFPGA_lite/18.1/hld/linux64/bin};
 17 append-path PATH {/opt/intelFPGA_lite/18.1/hld/bin};
 18 append-path PATH {/opt/intelFPGA_lite/18.1/quartus/sopc_builder/bin};
 19 
 20 setenv QSYS_ROOTDIR {/opt/intelFPGA_lite/18.1/quartus/sopc_builder/bin};
 21 setenv QUARTUS_64BIT {1};

 23 setenv AOCL_BOARD_PACKAGE_ROOT {/opt/intelFPGA_lite/18.1/hld/board/c5soc};

 25 prepend-path LD_LIBRARY_PATH {/opt/intelFPGA_lite/18.1/hld/host/linux64/lib:/opt/intelFPGA_lite/18.1/hld/board/c5soc/linux64/li    b};
 26 setenv INTELFPGAOCLSDKROOT {/opt/intelFPGA_lite/18.1/hld};
 27 setenv QUARTUS_ROOTDIR_OVERRIDE {/opt/intelFPGA_lite/18.1/quartus};
 28 setenv TCL_LIBRARY {/opt/intelFPGA_lite/18.1/quartus/linux64/tcl8.6};

```
more
![image](https://user-images.githubusercontent.com/22982301/70494072-e449f680-1b44-11ea-872d-2b82e030e821.png)

**Comment by lutherstrike** [comment]
Thank you so much!
Intel makes it too hard to notice there is still a Stand-Alone SDK, they don't even mention that in any doc I can find from their official website...
I will try this.
