### ISSUE TITLE
OpenCL SDK License issue in Quartus 16.1 lite edition (DE1_SoC)

### ISSUE THREAD

**Issue by ArjunaDeSoysa** [thinkoco/c5soc_opencl#3]
I installed the Quartus 16.1 lite edition(No License required). But in compiling process(make .aocx file) it asking for license file. Some one please help me to solve this problem.  
![capture](https://user-images.githubusercontent.com/35629589/35208815-c8eac9c2-ff7c-11e7-81e1-1f450671a690.PNG)

**Comment by thinkoco** [comment]
Yes，Quartus lite edition you need an opencl license to support it working.

**Comment by thinkoco** [comment]
@ArjunaDeSoysa Quartus 16.1 lite edition no need Quartus license and contains some  free IPs.When compiling opencl project ，you need an opencl license.

**Comment by ArjunaDeSoysa** [comment]
Thank you for the replying.. So its mean i have to buy that license file.

**Comment by ArjunaDeSoysa** [comment]
Can you please tell me is there any other solutions expect buying license
file. Because it is very expensive for me. I am university student.

**Comment by thinkoco** [comment]
@ArjunaDeSoysa  Maybe,you can ask your teacher to apply for a trial license form terasic. I'm not sure that you can get  one,but you can try it.

**Comment by ArjunaDeSoysa** [comment]
Ok I'll try it..thank you very much for replying....
