### ISSUE TITLE
是为什么不支持DE0-nano呢？

### ISSUE THREAD

**Issue by ash-liu** [thinkoco/c5soc_opencl#6]
Hi，你好。我想了解下，是什么原因不支持DE0-nano开发板呢？谢谢

**Comment by thinkoco** [comment]
@ash-liu Hi,您好。对于未能支持de0-nano表示抱歉，主要原因如下：
1.de0-nano 板上无video的DA或HDMI芯片，无法硬件直接支持。当然X2go的以太网方式访问应该是可行的。
2.此前想过使用 arduino tft 模块显示，驱动则使用tftfb。但发现SPI或tftfb的GPIO接口的效率并不是太高，可能达不到理想的帧率。目前没有太多linux驱动编写方面的经验，无法编写或优化驱动。此外，在taobao上购置的tft缺货漏发，因此一直搁置中。
3.terasic的MTL2屏幕模块也是一个不错的选择，也使用altera video IP的驱动，但是我没有这个模块。

**Comment by ash-liu** [comment]
哦，明白。非常感谢您的答复！另外您在论坛上的文章非常棒，给了我很大帮助，感谢您！
