### ISSUE TITLE
BSP for De0-nano-soc board

### ISSUE THREAD

**Issue by roddregs** [thinkoco/c5soc_opencl#7]
@thinkoco 
Sir, is there BSP for De0-nano-soc board that is downloadble online? 
Thank you.

**Comment by thinkoco** [comment]
@roddregs Hi,sorry for no de0-nano-soc being supported. I don't have a de0-nano-soc board. Maybe,you can ask terasic for de0-nano-soc VNC image which support desktop through ethernet.
